
rm 1024_results/*
cd 1024/
#for file in temp_dense_70.dat temp_dense_80.dat temp_dense_90.dat 
for file in temp_dense_10.dat temp_dense_20.dat temp_dense_30.dat temp_dense_40.dat temp_dense_50.dat temp_dense_60.dat temp_dense_70.dat temp_dense_80.dat temp_dense_90.dat 
#for file in denseNet_weights.txt mobileNetV2_weights.txt mobileNet_weights.txt resnetV2_weights.txt resnet_weights.txt vgg16_weights.txt vgg19_weights.txt 
do
echo $file
cd ..



./cHHT_sCSR_noexpand_HP.sh /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file >& 1024_results/HHT_CSR_vector8-$file.out 
wait
#./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 1 5 8 >& 1024_results/HHT_CSR_vector8-$file.out &                                                                                                                                                                                                                                       
./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 1 1 8 >& 1024_results/CSR_vector8-$file.out &                                                                                                                                                                                                                                       
./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 1 1 1 >& 1024_results/CSR_scalar-$file.out &                                                                                                                                                                                                                                       
./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 0 0 1 >& 1024_results/Dense_scalar-$file.out &                                                                                                                                                                                                                                       
./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 0 0 8 >& 1024_results/Dense_vector8-$file.out &                                                                                                                                                                                                                                       
#Express

./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 1 4 1 >& 1024_results/Exp_CSR_scalar-$file.out &                                                                                                                                                                                                                                       
./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 1 4 8 >& 1024_results/Exp_CSR_vector8-$file.out &                                                                                                                                                                                                                                       


./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 3 4 1 >& 1024_results/Exp_RL_scalar-$file.out &                                                                                                                                                                                                                                       
./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 3 4 8 >& 1024_results/Exp_RL_vector8-$file.out &                                                                                                                                                                                                                                       
./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 3 3 1 >& 1024_results/RL_scalar-$file.out &                                                                                                                                                                                                                                       
#./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 3 3 8 >& 1024_results/RL_vector8-$file.out &                                                                                                                                                                                                                                       

./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 2 4 1 >& 1024_results/Exp_BV_scalar-$file.out &                                                                                                                                                                                                                                       
#./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 2 4 8 >& 1024_results/Exp_BV_vector8-$file.out &                                                                                                                                                                                                                                       
./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 2 2 1 >& 1024_results/BV_scalar-$file.out &                                                                                                                                                                                                                                       
#./../../build/spike --dc=32768:1:32 --isa=RV32IMAFDCV --varch=v256:e32:s256 --timing=timings.txt ../../../../riscv-pk/build/pk a.out 1 0 /home/UNT/sa0659/RISCV/spike/riscv-flash/tests/spmv/1024/$file 2 2 8 >& 1024_results/BV_vector8-$file.out &                                                                                                                                                                                                                                       
wait
cd 1024
done
